### PR TITLE
fixes, cleanup and lint

### PR DESCRIPTION
**Pull request by webjay**
We use your great project a lot now at x.ai, so a huge thanks from the team.

What I've done:

- removed Procfile as Heroku can figure it out by looking at `"start": "node app.js"` in package.json.
- fixed some bugs.
- the code now gets a ✓ from [jshint.com](http://jshint.com/).
- if it looses database connection, it will retry every 5 seconds.

### CODE REVIEW

**Comment by andrewvy** [comment]
Sorry for the super delayed reply, I'm not sure why I'm not getting these notifications anymore..

A huge thank you for your time to do some clean-up work, I'll review it and get back to you! Looks really nice so far!

**Comment by dblock** [comment]
I am here to help a little, @webjay if you rebase/squash this I will merge it.

**Comment by andrewvy** [comment]
This one may be too outdated to be merged in. Major file structure changes happened since this PR.

**Comment by dblock** [comment]
Yeah, I think a lot of good things here can be redone over the current state of affairs. All I can tell @webjay is that you'll get a responsive group of maintainers now if you are ok doing the work twice!

**Comment by dblock** [comment]
I cherry picked things from here in https://github.com/andrewvy/slack-pongbot/pull/22 and https://github.com/andrewvy/slack-pongbot/pull/19.

**Pull request closed without merging**
