### PR TITLE
Enhancement + Leaderboard page

### PR DESCRIPTION
**Pull request by geoffrey**
Thanks for the awesome work on this bot!

Here are some small improvements that we are using + a leaderboard page and some doc for non technical people.

Commands improvements:
- [x] Respond to a challenge with `pongbot ok` `pongbot no`
- [x] Challenge someone on singles with `pongbot <challenge|vs> jonathan` (no need for the word `single(s)`)

Leaderboard page:
- [x] New API `/leaderboard` endpoint 
- [x] Tests
- [x] Accessible via `/info`
  screen shot 2015-07-06 at 7 14 04 pm

### CODE REVIEW

**Comment by andrewvy** [comment]
Cool, code looks good! Thanks for catching that semi-colon too.

Though, is there a reason you chose to hit the chat endpoint for the leaderboard instead of using the players api? https://github.com/andrewvy/slack-pongbot/blob/master/lib/app.js#L25 :)

**Comment by geoffrey** [comment]
Two reasons:
 -  [x] The `/players` API endpoint lack the sorting/limit/exclusion of players with no games that the command leaderboard already take into consideration.
 - [x] lack of time, was lazy and just wanted a way to print what slack `pongbot leaderboard` was printing =D

**Comment by dblock** [comment]
This is nice work. 

As a next step, now that there's help, I think it would be cool to tie commands like `pongbot help` to the current instance of pongbot instead of just linking to github. Furthermore instructions in README duplicate a lot of what's in those pages, so something should DRY them. 

PS: I'd also love this for https://github.com/dblock/slack-gamebot/issues/22.

**Comment by geoffrey** [comment]
@andrewvy I made the changes by creating a new endpoint with tests, what do you think about it ?

**Comment by andrewvy** [comment]
Good to go! Thanks for the contribution, this looks awesome! :+1:

**Pull request merged**
